### ISSUE TITLE
Client side - add new tab "extra report" 

### ISSUE THREAD

**Issue by mayasma** [mohamadir/15-minutes#23]
### Tasks
- [x] #1 add new tab 
- [x] #2 add description about the importance of reporting 
- [ ] #3 add links of another reports

**Comment by mohamadir** [comment]
ok great.
